import { createEnv } from "@t3-oss/env-nextjs";
import { BUILD_ENV } from "@mocanetwork/airkit";

import { z } from "zod";

export enum MocaChain {
  DEVNET = "devnet",
  TESTNET = "testnet",
}

export const env = createEnv({
  server: {
    PARTNER_PRIVATE_KEY: z.string(),
    SIGNING_ALGORITHM: z.enum(["ES256", "RS256"]).default("ES256"),
    NEXT_PRIVATE_TEST_ADDRESS: z.string().optional(),
    SPOTIFY_CLIENT_ID: z.string().optional(),
    SPOTIFY_CLIENT_SECRET: z.string().optional(),
    TWITTER_CLIENT_ID: z.string().optional(),
    TWITTER_CLIENT_SECRET: z.string().optional(),
    DISCORD_CLIENT_ID: z.string().optional(),
    DISCORD_CLIENT_SECRET: z.string().optional(),
    NEXTAUTH_SECRET: z.string(),
    NEXTAUTH_URL: z.string().optional(),
  },
  client: {
    NEXT_PUBLIC_PARTNER_ID: z.string(),
    NEXT_PUBLIC_ISSUER_DID: z.string(),
    NEXT_PUBLIC_ISSUE_PROGRAM_ID: z.string().optional(),
    // Per-route default issuance programs (optional)
    NEXT_PUBLIC_SPOTIFY_PROGRAM_ID: z.string().optional(),
    NEXT_PUBLIC_TWITTER_PROGRAM_ID: z.string().optional(),
    NEXT_PUBLIC_DISCORD_PROGRAM_ID: z.string().optional(),
    NEXT_PUBLIC_ETHOS_PROGRAM_ID: z.string().optional(),
    NEXT_PUBLIC_WALLET_PROGRAM_ID: z.string().optional(),
    NEXT_PUBLIC_AIRKIT_PROGRAM_ID: z.string().optional(),
    NEXT_PUBLIC_HEADLINE: z.string().optional(),
    NEXT_PUBLIC_REOWN_PROJECT_ID: z.string(),
    NEXT_PUBLIC_APP_NAME: z.string(),
    NEXT_PUBLIC_BUILD_ENV: z.enum(BUILD_ENV),
    NEXT_PUBLIC_MOCA_CHAIN: z.enum(MocaChain),
    NEXT_PUBLIC_THEME: z.enum(["light", "dark", "system"]),
    NEXT_PUBLIC_SPOTIFY_CLIENT_ID: z.string().optional(),
    NEXT_PUBLIC_ANNOUNCEMENT_TITLE: z.string().optional(),
    NEXT_PUBLIC_ANNOUNCEMENT_MESSAGE: z.string().optional(),
    NEXT_PUBLIC_ANNOUNCEMENT_ID: z.string().optional(),
    NEXT_PUBLIC_ANNOUNCEMENT_TTL_DAYS: z.coerce.number().optional(),
    NEXT_PUBLIC_MOCK_ISSUANCE: z.coerce.number().optional(),
  },
  runtimeEnv: {
    PARTNER_PRIVATE_KEY: process.env.PARTNER_PRIVATE_KEY,
    NEXT_PRIVATE_TEST_ADDRESS: process.env.NEXT_PRIVATE_TEST_ADDRESS,
    SPOTIFY_CLIENT_ID: process.env.SPOTIFY_CLIENT_ID,
    SPOTIFY_CLIENT_SECRET: process.env.SPOTIFY_CLIENT_SECRET,
    TWITTER_CLIENT_ID: process.env.TWITTER_CLIENT_ID,
    TWITTER_CLIENT_SECRET: process.env.TWITTER_CLIENT_SECRET,
    DISCORD_CLIENT_ID: process.env.DISCORD_CLIENT_ID,
    DISCORD_CLIENT_SECRET: process.env.DISCORD_CLIENT_SECRET,
    NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
    NEXTAUTH_URL: process.env.NEXTAUTH_URL,
    NEXT_PUBLIC_PARTNER_ID: process.env.NEXT_PUBLIC_PARTNER_ID,
    NEXT_PUBLIC_ISSUER_DID: process.env.NEXT_PUBLIC_ISSUER_DID,
    NEXT_PUBLIC_ISSUE_PROGRAM_ID: process.env.NEXT_PUBLIC_ISSUE_PROGRAM_ID,
    NEXT_PUBLIC_SPOTIFY_PROGRAM_ID: process.env.NEXT_PUBLIC_SPOTIFY_PROGRAM_ID,
    NEXT_PUBLIC_TWITTER_PROGRAM_ID: process.env.NEXT_PUBLIC_TWITTER_PROGRAM_ID,
    NEXT_PUBLIC_DISCORD_PROGRAM_ID: process.env.NEXT_PUBLIC_DISCORD_PROGRAM_ID,
    NEXT_PUBLIC_ETHOS_PROGRAM_ID: process.env.NEXT_PUBLIC_ETHOS_PROGRAM_ID,
    NEXT_PUBLIC_WALLET_PROGRAM_ID: process.env.NEXT_PUBLIC_WALLET_PROGRAM_ID,
    NEXT_PUBLIC_AIRKIT_PROGRAM_ID: process.env.NEXT_PUBLIC_AIRKIT_PROGRAM_ID,
    NEXT_PUBLIC_HEADLINE: process.env.NEXT_PUBLIC_HEADLINE,
    NEXT_PUBLIC_REOWN_PROJECT_ID: process.env.NEXT_PUBLIC_REOWN_PROJECT_ID,
    NEXT_PUBLIC_APP_NAME: process.env.NEXT_PUBLIC_APP_NAME,
    NEXT_PUBLIC_BUILD_ENV: process.env.NEXT_PUBLIC_BUILD_ENV,
    NEXT_PUBLIC_MOCA_CHAIN: process.env.NEXT_PUBLIC_MOCA_CHAIN,
    SIGNING_ALGORITHM: process.env.SIGNING_ALGORITHM,
    NEXT_PUBLIC_THEME: process.env.NEXT_PUBLIC_THEME,
    NEXT_PUBLIC_SPOTIFY_CLIENT_ID: process.env.NEXT_PUBLIC_SPOTIFY_CLIENT_ID,
    NEXT_PUBLIC_ANNOUNCEMENT_TITLE: process.env.NEXT_PUBLIC_ANNOUNCEMENT_TITLE,
    NEXT_PUBLIC_ANNOUNCEMENT_MESSAGE: process.env.NEXT_PUBLIC_ANNOUNCEMENT_MESSAGE,
    NEXT_PUBLIC_ANNOUNCEMENT_ID: process.env.NEXT_PUBLIC_ANNOUNCEMENT_ID,
    NEXT_PUBLIC_ANNOUNCEMENT_TTL_DAYS: process.env.NEXT_PUBLIC_ANNOUNCEMENT_TTL_DAYS,
    NEXT_PUBLIC_MOCK_ISSUANCE: process.env.NEXT_PUBLIC_MOCK_ISSUANCE,
  },
});

export const isProduction = process.env.NODE_ENV === "production";
